MERGE dbo.Shindig AS TARGET
USING (VALUES ('apicon-new-york-2025',                           1, 1, 3, 'US', 'NY',  '2025-09-29', '2025-10-02', 'APIcon New York 2025',                           'New York',     'New York Marriott at the Brooklyn Bridge', 'America/​New_York', 'https://apiconference.net/new-york/'),
              ('devopscon-new-york-2025',                        1, 1, 3, 'US', 'NY',  '2025-09-29', '2025-10-02', 'DevOps Con New York 2025',                       'New York',     'New York Marriott at the Brooklyn Bridge', 'America/​New_York', 'https://devopscon.io/new-york/'),
              ('techoroma-netherlands-2025',                     1, 1, 3, 'NL', 'UT',  '2025-10-27', '2025-10-29', 'Techorama 2025 Netherlands',                     'Urecht',       'Kinepolis Jaarbeurs Utrecht',              'Europe/​Amsterdam', 'https://www.techorama.nl/'),
              ('prairie-dev-con-winnipeg-2025',                  1, 1, 3, 'CA', 'MB',  '2025-09-22', '2025-09-23', 'Prairie Dev Con 2025 Winnipeg',                  'Winnipeg',     'Canad Inns Destination Centre Polo Park',  'America/​Winnipeg', 'https://www.prairiedevcon.com/'),
              ('ncd-porto-2025',                                 1, 1, 3, 'PT', '13',  '2025-10-20', '2025-10-24', 'NDC Porto 2025',                                 'Porto',        'Alfândega Porto Congress Centre',          'Europe/​Lisbon',    'https://ndcporto.com/'),
              ('apicon-berlin-2025',                             1, 1, 3, 'DE', 'BE',  '2025-10-21', '2025-10-23', 'APIcon Berlin 2025',                             'Berlin',       'Maritim proArte Hotel',                    'Europe/​Berlin',    'https://apiconference.net/berlin/'),
              ('serverless-architecture-conference-berlin-2025', 1, 1, 3, 'DE', 'BE',  '2025-10-21', '2025-10-23', 'Serverless Architecture Conference Berlin 2025', 'Berlin',       'Maritim proArte Hotel',                    'Europe/​Berlin',    'https://apiconference.net/berlin/'),
              ('build-stuff-2025',                               1, 1, 3, 'LT', '58',  '2025-12-03', '2025-12-05', 'Build Stuff 2025',                               'Vilnius',      'Radisson Blu Hotel Lietuva',               'Europe/​Vilnius',   'https://buildstuff.events/'),
              ('atlanta-cloud-conference-2025',                  1, 1, 3, 'US', 'GA',  '2025-04-26', '2025-04-26', 'Atlanta Cloud Conference 2025',                  'Atlanta',      'Kennesaw State University',                'America/​New_York', 'https://atlcloudconf.com/'),
              ('stir-trek-2025',                                 1, 1, 3, 'US', 'OH',  '2025-05-02', '2025-05-02', 'Stir Trek 2025',                                 'Columbus',     'AMC Easton 30',                            'America/​New_York', 'https://stirtrek.com/'),
              ('devup-2025',                                     1, 1, 3, 'US', 'MO',  '2025-08-06', '2025-08-08', 'dev up 2025',                                    'St. Charles',  'St. Charles Convention Center',            'America/​Chicago',  'https://www.devupconf.org/'),
              ('beer-city-code-2025',                            1, 1, 3, 'US', 'MI',  '2025-08-08', '2025-08-09', 'Beer City Code 2025',                            'Grand Rapids', 'Calvin University - Fine Arts Center',     'America/​Detroit',  'https://beercitycode.com/'),
              ('kcdc-2025',                                      1, 1, 3, 'US', 'MO',  '2025-08-13', '2025-08-15', 'KCDC 2025',                                      'Kansas City',  'Kansas City Convention Center',            'America/​Chicago',  'https://kcdc.info/'),
              ('devconf-2025',                                   1, 1, 3, 'PL', '10',  '2025-10-08', '2025-10-10', 'DevConf 2025',                                   'Łódź',         'EXPO Łódź',                                'Poland',           'https://devconf.pl/'),
              ('azure-fest-2025',                                1, 1, 3, 'NL', 'UT',  '2025-09-17', '2025-09-17', 'Azure Fest 2025',                                'Nieuwegein',   'Sopra Steria',                             'Europe/​Amsterdam', 'https://azurefest.nl/'),
              ('cloudbrew-2025',                                 1, 1, 3, 'BE', 'VAN', '2025-12-11', '2025-12-12', 'Cloudbrew 2025',                                 'Mechelen',     'Lamot',                                    'Europe/​Brussels',  'https://www.cloudbrew.be/'),
              ('dotnet-developer-conference-25',                 1, 1, 3, 'DE', 'NW',  '2025-11-24', '2025-11-27', '.NET Developer Conference ''25',                 'Köln',         'Pullman Colegne',                          'Europe/​Berlin',    'https://www.dotnet-developer-conference.de/'))
AS SOURCE (Permalink,
           IsEnabled,
           ShindigTypeId,
           ShindigStatusId,
           CountryCode,
           CountryDivisionCode,
           StartDate,
           EndDate,
           ShindigName,
           City,
           Venue,
           TimeZoneId,
           ShindigUrl)
ON TARGET.Permalink = SOURCE.Permalink
WHEN MATCHED THEN UPDATE SET TARGET.ShindigTypeId       = SOURCE.ShindigTypeId,
                             TARGET.ShindigStatusId     = SOURCE.ShindigStatusId,
                             TARGET.ShindigName         = SOURCE.ShindigName,
                             TARGET.CountryCode         = SOURCE.CountryCode,
                             TARGET.CountryDivisionCode = SOURCE.CountryDivisionCode,
                             TARGET.City                = SOURCE.City,
                             TARGET.Venue               = SOURCE.Venue,
                             TARGET.StartDate           = SOURCE.StartDate,
                             TARGET.EndDate             = SOURCE.EndDate,
                             TARGET.TimeZoneId          = SOURCE.TimeZoneId,
                             TARGET.ShindigUrl          = SOURCE.ShindigUrl,
                             TARGET.IsEnabled           = SOURCE.IsEnabled
WHEN NOT MATCHED THEN INSERT (Permalink,
                              ShindigTypeId,
                              ShindigStatusId,
                              ShindigName,
                              CountryCode,
                              CountryDivisionCode,
                              City,
                              Venue,
                              StartDate,
                              EndDate,
                              TimeZoneId,
                              ShindigUrl,
                              IsEnabled)
                      VALUES (SOURCE.Permalink,
                              SOURCE.ShindigTypeId,
                              SOURCE.ShindigStatusId,
                              SOURCE.ShindigName,
                              SOURCE.CountryCode,
                              SOURCE.CountryDivisionCode,
                              SOURCE.City,
                              SOURCE.Venue,
                              SOURCE.StartDate,
                              SOURCE.EndDate,
                              SOURCE.TimeZoneId,
                              SOURCE.ShindigUrl,
                              SOURCE.IsEnabled)
WHEN NOT MATCHED BY SOURCE THEN DELETE;
GO